#!/bin/bash

mkdir -p /var/lib/megam/megamgulpd

#chown megam:megam /var/run/megam/megamgulpd

#chown megam:megam /var/log/megam/megamgulpd


systemctl start megamgulpd || echo "megamgulpd could not be started. Try manually with service megamgulpd start" >/dev/stdout

