#!/bin/sh

chown megam:megam /var/run/megam/megamgogs

chown megam:megam /var/log/megam/megamgogs

chown -R  megam:megam /var/lib/megam/megamgogs/repos

initctl reload-configuration

service megamgogs start || echo "megamgogs could not be started. Try manually with service megamgogs start"
