#!/bin/sh

#chown megam:megam /var/run/megam/megametcd

#chown megam:megam /var/log/megam/megametcd



systemctl start etcd.service || echo "etcd could not be started. Try manually with service etcd start" >/dev/stdout
