#!/bin/sh

cd usr/share/megam/verticenilavu

bundle update

bundle install

cd ../../../..

fpm -s dir -t rpm  -p "$MEGAM_HOME"  -f  --iteration $3 -n $1 -v $2 -d "verticecommon,git-core,curl,rake,zlib-devel,zlib,readline-devel,libyaml-devel,libxml2-devel,openssl-devel,ruby,ruby-devel" --before-install ./preinst --after-install ./postinst --before-upgrade ./preupgrd --before-remove ./prerm --rpm-init ./etc/etc/systemd/system/verticenilavu.service --license "Apache V2" --vendor "Megam Systems" --category "infrastructure" --maintainer "Megam Maintainer info@megam.io" --url " http://docs.megam.io/docs/vertice" --description "The userinterface using Ruby on Rails which provides the one click launcher for
 Megam Vertice. This is connected to the Vertice gateway (API server) only
 .
 This provides a marketplace, ability to manage storage like S3 utilizing ceph storage, launch
 application, vms, containers (docker), stream logs and monitor and bill them.
 .
 This package contains an awesome userinterface based on Ruby on Rails for Megam Vertice." ./usr/share/megam/verticenilavu
