#!/bin/bash

cat > //var/lib/megam/env.sh <<EOF
initctl set-env MEGAM_HOME='/var/lib/megam'
EOF

mkdir -p /var/lib/megam/verticegulpd /var/lib/megam/gulp/

initctl reload-configuration

service verticegulpd  start || echo " could not be started. Try manually with service  start"
