#!/bin/sh

cat > //etc/init/megamvarai.conf <<EOF
#!upstart
description "Node.js visual designer server"
author      "Megam Systems"

start on startup
stop on shutdown

script
    export HOME="/root"
    echo $$ > /var/run/megam/megamvarai/megamvarai.pid
    exec sudo /usr/bin/node /usr/share/megam/megamvarai/varai.js >> /var/log/megam/megamvarai/megamvarai.log 2>&1
end script

pre-start script
        mkdir -p -m 0775 /var/run/megam/megamvarai
    # Date format same as (new Date()).toISOString() for consistency
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Starting" >> /var/log/megam/megamvarai/megamvarai.log
end script

pre-stop script
    rm /var/run/megam/megamvarai/megamvarai.pid
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Stopping" >> /var/log/megam/megamvarai/megamvarai.log
end script
EOF


echo "starting megamvarai"
sudo start megamvarai
echo "started"
