#!/bin/sh

if [ -d "/usr/share/megam/cadvisor" ]; then
  rm -r /usr/share/megam/cadvisor
fi

if [ -d "/var/lib/megam/cadvisor" ]; then
  rm -r /var/lib/megam/cadvisor
fi

if [ -d "/var/run/megam/cadvisor" ]; then
  rm -r /var/run/megam/cadvisor
fi

if [ -d "/var/log/megam/cadvisor" ]; then
  rm -r /var/log/megam/cadvisor
fi
