#!/bin/bash

# we create an openvswitch bridge named "megdock"
openvswitch_bridge() {
mkdir -p /var/lib/megam/megamdocker

ovs-vsctl add-br megdock

echo "[megamdocker] created openvswitch bridge : megdock"  >> /var/log/upstart/megamdocker.log

cp /usr/share/megam/megamdocker/bin/pipework /var/lib/megam/
echo "[megamdocker] copied pipework into megam_home"  >> /var/log/upstart/megamdocker.log
}

docker_upstart() {
  service docker stop

  while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
		[ "$Mask" = "00000000" ] && \
		interface="$Iface" && \
		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
		ipaddr=${ipaddr#* inet } && \
		ipaddr=${ipaddr%%/*} && \
		break
	done < /proc/net/route
  echo "[megamdocker] starting docker in detached mode at $ipaddr:2375" >> /var/log/upstart/megamdocker.log

cat > /etc/init/dockerservice.conf <<EOF
description "Docker cluster scheduler for baremetal (https://console.megam.io)"
author "Megam Systems(https://www.megam.io)"
# When to start the servicee
start on runlevel [2345]
start on (started networking)
start on (local-filesystems)
# When to stop the service
stop on runlevel [016]
stop on (stopping networking)
stop on (stopped dockerservice)
script
  echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) dockerservice starting" >> /var/log/megam/dockerservice.log
  exec docker -H tcp://$ipaddr:2375 -d  >> /var/log/megam/dockerservice.log 2>&1
end script
post-start script
    PID=`status megamdocker | egrep -oi '([0-9]+)$' | head -n1`
    echo $PID > /var/run/megam/dockerservice.pid
end script
EOF

  start dockerservice

}

docker_upstart
openvswitch_bridge

## voila start the service now (megamdocker)
service megamdocker start || echo "megamdocker could not be started. Try manually with service megamdocker start"
