#!/bin/bash

cat > //var/lib/megam/env.sh <<EOF
initctl set-env MEGAM_HOME='/var/lib/megam'
EOF

mkdir -p /var/lib/megam/megamgulpd /var/lib/megam/gulp/

initctl reload-configuration

service megamgulpd start || echo "megamgulpd could not be started. Try manually with service megamgulpd start"

