require "rake"
require "../../version.rb"
require "./config.rb"
puts ">> ------------- [#{MegamPkg::Ger::CONFIG[:name]} #{MegamPkg::Ger::VERSION}]"
task :default => :precise

build_dir ="build"
trusty_dir ="trusty"
build_trusty_dir ="build/trusty"

precise_dir ="precise"
build_precise_dir ="build/precise"

task :clean do
  rm_rf build_trusty_dir
  rm_rf build_dir
  rm_rf build_precise_dir
end


task :trusty => [:inittrusty_setup, :initcib, :clone] do
  system './g', MegamPkg::Ger::CONFIG[:name], MegamPkg::Ger::VERSION
  system './ng', MegamPkg::Ger::CONFIG[:name_node], MegamPkg::Ger::VERSION
end

task :inittrusty_setup do
  mkdir_p build_dir
  mkdir_p build_trusty_dir
  Rake::FileList[trusty_dir +"/**"].each do |f|
    target = File.join build_trusty_dir,  File.basename(f)
    cp_r f, target
  end
  Dir.chdir build_trusty_dir
end

task :initcib do
  mkdir_p "cloudinabox/src/github.com/megamsys"
end

task :initprecise_setup do
  mkdir_p build_dir
  mkdir_p build_precise_dir
  Rake::FileList[precise_dir +"/**"].each do |f|
    target = File.join build_precise_dir,  File.basename(f)
    cp f, target
  end
  Dir.chdir build_precise_dir
end

task :precise => [:initprecise_setup, :clone] do
  system './g', MegamPkg::Ger::CONFIG[:name], MegamPkg::Ger::VERSION
end


task :clone do
  if !File.exists? 'cloudinabox/src/github.com/megamsys/cloudinabox/'
   Dir.chdir 'cloudinabox/src/github.com/megamsys'
   system "git clone " + MegamPkg::Ger::CONFIG[:git]
 end
 Dir.chdir '../../../../'
end

task :copydeb do
  if !File.exists? '*.deb'
   cp_r './cloudinabox/*.deb' '../../../'
  end
end
