#!/bin/sh
cd tap
npm install

pkgr package ./ --user=megam --group=megam --maintainer="Thomas Alrin<alrin@megam.co.in>, Raj Thilak <rajthilak@megam.co.in>, Kishorekumar Neelamegam<nkishore@megam.co.in>, Megam Systems <gomegam@megam.co.in>" --runner='upstart-1.5' --dependencies=nodejs nodejs-legacy openjdk-7-jre elasticsearch --after-install=$PWD/postinst --before-install=$HOME/code/megam/workspace/packager/megamanalytics/ubuntu/build/trusty/preinst --after-remove=$HOME/code/megam/workspace/packager/megamanalytics/ubuntu/build/trusty/postrm --before-remove=$HOME/code/megam/workspace/packager/megamanalytics/ubuntu/build/trusty/prerm --auto  --clean --name=megamanalytics --version=0.5 --iteration=1  --edge  --homepage="http://www.gomegam.com" --description="Megam - Online log for megam" --license="Apache" --home="/usr/share/megam"


