#!/bin/sh

cat > //etc/init/megamanalytics.conf <<EOF
#!upstart
description "Megam logs(https://console.megam.io)"
author      "Megam Systems(https://www.megam.io)"

# When to start the servicee
start on runlevel [2345]
start on (started networking)

# When to stop the service
stop on runlevel [016]
stop on (stopping networking)
stop on (stopped megamanalytics)
stop on shutdown

pre-start script
    [ -d /var/run/megam ]  || mkdir -p /var/run/megam
    [ -d /var/log/megam ]  || mkdir -p /var/log/megam
    [ -d /var/log/megam/megamanalytics ] || mkdir -p /var/log/megam/megamanalytics
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Starting" >> /var/log/megam/megamanalytics/megamanalytics.log
end script

script
    echo $$ > /var/run/megam/megamanalytics.pid
    exec sudo /usr/bin/node /usr/share/megam/megamanalytics/tap_monitor.js >> /var/log/megam/megamanalytics/megamanalytics.log 2>&1
end script

pre-stop script
    rm /var/run/megam/megamanalytics.pid
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Stopping" >> /var/log/megam/megamanalytics/megamanalytics.log
end script
EOF

sudo start megamanalytics
