#!/bin/sh
echo "==============> post remove start <======================"

[ -d /var/log/megam/megamdesigner ] && rm -rf /var/log/megam/megamdesigner

[ -d /var/run/megam/megamdesigner ] && rm -rf /var/run/megamdesigner

[ -d /usr/share/megam/megamdesigner ] && rm -rf /usr/share/megam/megamdesigner

[ -d /etc/megamdesigner ] && rm -rf /etc/megamdesigner


echo "==============> post remove end<======================"
