#!/bin/bash

mkdir -p /var/lib/megam/verticevnc

cd /var/megam/


  wget http://nodejs.org/dist/v0.10.30/node-v0.10.30.tar.gz
  tar xzvf node-v* && cd node-v*tar xzvf node-v* && cd node-v*
  sudo yum install gcc gcc-c++
 ./configure
  make
  sudo make install


cp /usr/local/bin/node usr/bin/node

mv /etc/init.d/verticevnc.service /etc/systemd/system/

cat >> /var/lib/megam/env.sh << EOF
MEGAM_HOME='/var/lib/megam/'
EOF

chmod 0755 /var/lib/megam/env.sh

systemctl enable verticevnc.service
systemctl start verticevnc.service
