#!/bin/sh
mkdir -p ./usr/share/megam/verticevnc/

cd ./usr/share/megam/verticevnc

npm install

cd ../../../../

fpm -s dir -t deb -p "$MEGAM_HOME"  -f  --iteration $3  -n $1 -v $2 -d "nodejs-legacy" --before-install ./preinst --after-install ./postinst --before-remove  ./prerm --after-remove ./postrm --deb-upstart ./etc/init/verticevnc --license "Apache V2" --vendor "Megam Systems" --category "infrastructure" --maintainer "Megam Maintainer info@megam.io" --url "http://docs.megam.io" --description "Description:
This package contains a nodejs based VNC server for Megam Verticevnc." ./usr/share/megam/verticevnc
