require "rake"
require "../version.rb"
require "./config.rb"
puts ">> ------------- [#{Pkg::Ger::CONFIG[:name]} #{Pkg::Ger::VERSION} #{Pkg::Ger::ITERATION}]"

megger = Pkg::Ger.new

nix_dir="nix"
build_dir ="build"

task :default => :trusty

task :clean do
  rm_rf build_dir
end

task :initnix do
  mkdir_p build_dir
  mkdir_p megger.build_halwa
end

task :nix => [:initnix] do
  Rake::FileList["#{megger.halwa}" + "/**"].each do |f|
   target = File.join megger.build_halwa,  File.basename(f)
    cp_r f, target
  end if File.exists?(megger.halwa)

  Dir.chdir megger.build_halwa
  system './g', Pkg::Ger::CONFIG[:name], Pkg::Ger::VERSION, Pkg::Ger::ITERATION
end

task :trusty   do
  megger.halwa=nix_dir
  megger.build_halwa="build/trusty"
  Rake::Task[:nix].invoke
end

task :centos7 do
  megger.halwa ="centos7"
  megger.build_halwa="build/centos7"
  Rake::Task[:nix].invoke
end


task :jessie do
  megger.halwa ="jessie"
  megger.build_halwa="build/jessie"
  Rake::Task[:nix].invoke
end
