require "rake"
require "./config.rb"
require "../builder.rb"

task :default => :trusty

task :clean do
  rm_rf Pkg::Config.build_dir
end

task :initnix do
  mkdir_p Pkg::Config.distro_build_dir
end

task :nix => [:initnix] do
  Pkg::Builder.new(Pkg::Config.distro_dir, Pkg::Config.distro_build_dir,Pkg::Config::PACKAGE).exec
end

task :trusty   do
  Pkg::Config.setup_distro("trusty")
  Rake::Task[:nix].invoke
end


task :centos7 do
  Pkg::Config.setup_distro("centos7")
  Rake::Task[:nix].invoke
end

task :xenial do
  Pkg::Config.setup_distro("xenial")
  Rake::Task[:nix].invoke
end
