#!/bin/sh

mkdir -p /var/log/megam/megamnilavu
mkdir -p /var/run/megam/megamnilavu

#set MEGAM_HOME for megamnilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/megamnilavu.env <<EOF
MEGAM_HOME='/var/lib/megam'
EOF

chmod 755 /var/lib/megam/megamnilavu.env

chmod 666 /usr/share/megam/megamnilavu/production.log

cd /usr/share/megam/megamnilavu

echo "starting megamnilavu" >/dev/stdout
sudo systemctl start megamnilavu.service
echo "started" >/dev/stdout

systemctl reload megamnilavu.service
