#!/bin/sh

mkdir -p /var/log/megam/megamnilavu

mkdir -p /var/run/megam/megamnilavu

#set MEGAM_HOME for megamnilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/megamnilavu.env <<EOF
MEGAM_HOME='/var/lib/megam'
EOF

chmod 755 /var/lib/megam/megamnilavu.env

#chmod 666 /usr/share/megam/megamnilavu/production.log

cp /usr/share/megam/megamnilavu/config/nilavu.yml /var/lib/megam/nilavu.yml

cp /etc/init.d/megamnilavu.service /etc/systemd/system/

cd /usr/share/megam/megamnilavu

gem install bundler

/usr/local/bin/bundle update

echo "megamnilavu installed."
