#!/bin/sh

cat > //etc/init/megamdesigner.conf <<EOF
#!upstart
description "node.js server"
author      "Megam Systems"

start on startup
stop on shutdown

script
    export HOME="/root"

    echo $$ > /var/run/megam/megamdesigner/megamdesigner.pid
    exec sudo /usr/bin/node /usr/share/megam/megamdesigner/varai.js >> /var/log/megam/megamdesigner/megamdesigner.log 2>&1
end script

pre-start script
    # Date format same as (new Date()).toISOString() for consistency
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Starting" >> /var/log/megam/megamdesigner/megamdesigner.log
end script

pre-stop script
    rm /var/run/megam/megamdesigner/megamdesigner.pid
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Stopping" >> /var/log/megam/megamdesigner/megamdesigner.log
end script
EOF



echo "starting megamdesigner"
sudo start megamdesigner
echo "started"


