#!/bin/sh
# this will have nothing. 
echo "==============> preinstall  start<======================"
mkdir -p /var/log/megam/megamdesigner
mkdir -p /var/run/megam/megamdesigner
chown megam:megam /var/run/megam/megamdesigner

chown megam:megam /var/log/megam/megamdesigner


echo "==============> preinstall end<======================"
