#!/bin/sh

if [ -d "/usr/share/megam/megamgulpd" ]; then
  rm -r /usr/share/megam/megamgulpd
fi

if [ -d "/var/lib/megam/megamgulpd" ]; then
  rm -r /var/lib/megam/megamgulpd
fi

if [ -d "/var/run/megam/megamgulpd" ]; then
  rm -r /var/run/megam/megamgulpd
fi

if [ -d "/var/log/megam/megamgulpd" ]; then
  rm -r /var/log/megam/megamgulpd
fi
