#!/bin/sh

mkdir -p ./usr/share/megam/megamgateway



fpm -s dir -t rpm -n megamgateway -v 0.1 --license "Apache" --vendor "Megam Systems" --maintainer "<rajthilak@megam.co.in>" --url "http://www.gomegam.com" --description "Megam common an empty package which just creates an user megam and group megam." ./usr/share/megam/megamgateway
