#!/bin/sh

[ -d /var/log/megam/verticenilavu ] && rm -rf /var/log/megam/verticenilavu

[ -d /var/lib/megam/site_settings.yml ] && rm -rf /var/lib/megam/site_settings.yml

[ -d /var/lib/megam/nilavu.conf ] && rm -rf /var/lib/megam/nilavu.conf

[ -d /var/lib/megam/regions.yml ] && rm -rf /var/lib/megam/regions.yml

[ -d /etc/runit ] && rm -rf /etc/runit

[ -d /etc/service/unicorn ] && rm -rf /etc/service/unicorn

[ -d /etc/service/nginx ] && rm -rf /etc/service/nginx

[ -d /etc/service/cron ] && rm -rf /etc/service/cron

[ -d /etc/service/rsyslog ] && rm -rf /etc/service/rsyslog

[ -d  /jemalloc] && rm -rf /jemalloc
