#!/bin/sh

mkdir -p /var/log/megam/verticenilavu

#set MEGAM_HOME for verticenilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/env.sh <<EOF
MEGAM_HOME='/var/lib/megam'
EOF

chmod 755 /var/lib/megam/env.sh

#ruby change
rm /usr/bin/ruby
rm /usr/bin/gem
ln -s /usr/bin/ruby2.3 /usr/bin/ruby
ln -s /usr/bin/gem2.3 /usr/bin/gem

cp /usr/share/megam/verticenilavu/config/nilavu.conf /var/lib/megam/nilavu.conf
cp /usr/share/megam/verticenilavu/config/site_settings.yml /var/lib/megam/site_settings.yml

cp /etc/init.d/verticenilavu.service /etc/systemd/system/

gem install bundler

cd /usr/share/megam/verticenilavu/
bundle install

systemctl enable verticenilavu
systemctl start verticenilavu
