## TO-DO so there is nothing significantly different in every Rakefile :) sweet.
## Maybe we should use thor and auto-generate Rakefile before we build.
## The tasks get driver from thor

require "rake"
require "./config.rb"
require "../common.rb"
require "../builder.rb"
require "../utils.rb"


task :default => :trusty

task :clean do
  Pkg::Utils.rmdir(Pkg::Common.build_dir)
end

task :initnix do
  Pkg::Utils.mkdir_p(Pkg::Common.distro_build_dir)
end

task :nix => [:initnix] do
  Pkg::Builder.new(Pkg::Common.distro_dir, Pkg::Common.distro_build_dir, Pkg::Config::PACKAGE).exec
end

task :trusty   do
  Pkg::Common.distro("trusty")
  Rake::Task[:nix].invoke
end

task :xenial do
  Pkg::Common.distro("xenial")
  Rake::Task[:nix].invoke
end

task :centos7 do
  Pkg::Common.distro("centos7")
  Rake::Task[:nix].invoke
end
