#!/bin/sh
#!/bin/sh
if [ -d "/usr/share/megam/megametcd" ]; then
  rm -r /usr/share/megam/megametcd
fi

if [ -d "/var/run/megam/megametcd" ]; then
  rm -r /var/run/megam/megametcd
fi

if [ -d "/var/log/megam/megametcd" ]; then
  rm -r /var/log/megam/megametcd
fi

