require "rake"
require "../version.rb"
require "./config.rb"
puts ">> ------------- [#{MegamPkg::Ger::CONFIG[:name]} #{MegamPkg::Ger::VERSION} #{MegamPkg::Ger::ITERATION}]"

megger = MegamPkg::Ger.new

nix_dir="nix"
build_dir ="build"

task :default => :trusty

task :clean do
  rm_rf build_dir
end

task :initnix do
  mkdir_p build_dir
  mkdir_p megger.build_halwa
end

#this overrides the nix/ stuff with halwa specific stuff.
task :nix => [:initnix] do
  Rake::FileList["#{megger.halwa}" +"/**"].each do |f|
    target = File.join megger.build_halwa,  File.basename(f)
    cp_r f, target
  end if File.exists?(megger.halwa)

  Dir.chdir megger.build_halwa
  mkdir_p "vertice/src/github.com/megamsys"
  Rake::Task[:clone].invoke
  system './g', MegamPkg::Ger::CONFIG[:name], MegamPkg::Ger::VERSION, MegamPkg::Ger::ITERATION
end

task :trusty   do
  megger.halwa=nix_dir
  megger.build_halwa="build/trusty"
  Rake::Task[:nix].invoke
end

task :centos7 do
  megger.halwa ="centos7"
  megger.build_halwa="build/centos7"
  Rake::Task[:nix].invoke
end

task :jessie do
  megger.halwa ="jessie"
  megger.build_halwa="build/jessie"
  Rake::Task[:nix].invoke
end

task :clone do
  if !File.exists? 'vertice/src/github.com/megamsys/vertice/'
   Dir.chdir 'vertice/src/github.com/megamsys'
   system "git clone " + MegamPkg::Ger::CONFIG[:git]
 end
 Dir.chdir '../../../../'
end
