#!/bin/sh
mkdir -p ./usr/share/megam/megamcib/bin

cd cloudinabox/src/github.com/megamsys/cloudinabox

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/cloudinabox.git

make build

cp -rf ./views/ ../../../../../usr/share/megam/megamcib
cp -rf ./static_source/ ../../../../../usr/share/megam/megamcib
cp -rf ./conf/ ../../../../../usr/share/megam/megamcib
cp cibd ../../../../../usr/share/megam/megamcib/bin

cd ../../../../../

fpm -s dir -t deb -p "$MEGAM_HOME"  -f  --iteration $3 -n $1 -v $2 -d "verticecommon, debconf, sqlite3, debconf-utils, whiptail, apt-utils" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --deb-upstart ./etc/systemd/system/megamcib --deb-templates ./templates --license "Apache V2" --vendor "Megam Systems" --category "infrastructure" --maintainer "Megam Maintainer info@megam.io" --url "http://docs.megam.io" --description "Description: command line which sets up OpenNebula, Ceph/LVM, Megam Vertice
OpenNebula is an open source virtual infrastructure engine. Ceph is an
open source unified cloud storage. Megam Vertice is an opensource platform
as service engine.
.
Vertice ONE (OpenNebula) extends the benefits of virtualization platforms from a
single physical resource to a pool of resources, decoupling the server not
only from the physical infrastructure but also from the physical location.
.
This package contains Megdc command line which make your datacenter cloud using
open source." ./usr/share/megam/megamcib
