#!/bin/sh
mkdir -p ./usr/share/megam/megamcib/bin

cd cloudinabox/src/github.com/megamsys/cloudinabox

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/cloudinabox.git

make build

cp -rf ./views/ ../../../../../usr/share/megam/megamcib
cp -rf ./static_source/ ../../../../../usr/share/megam/megamcib
cp -rf ./conf/ ../../../../../usr/share/megam/megamcib
cp cibd ../../../../../usr/share/megam/megamcib/bin

cd ../../../../../

fpm -s dir -t deb -n $1 -v $2 -d "verticecommon, debconf, sqlite3, debconf-utils, whiptail, apt-utils" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --deb-upstart ./etc/systemd/system/megamcib --deb-templates ./templates --license "Apache" --vendor "Megam Systems" --maintainer "<thomasalrin@megam.io>" --url "https://www.megam.io" --description "Megdc base seed daemon" ./usr/share/megam/megamcib
