#!/bin/sh

chown megam:megam /var/run/megam/megamgogs

chown megam:megam /var/log/megam/megamgogs

chown megam:megam /var/lib/megam/megamgogs

chown -R  megam:megam /var/lib/megam/megamgogs/repos

chown megam:megam /usr/share/megam/megamgogs

chown -R megam:megam /usr/share/megam/megamgogs


systemctl start megamgogs || echo "megamgogs could not be started. Try manually with service megamgogs start" >/dev/stdout
