#!/bin/sh

mkdir -p ./usr/share/megam

fpm -s dir -t deb -n $1 -v $2 --after-install ./postinst --after-remove ./postrm --license "Apache" --vendor "Megam Systems" --maintainer "<info@megam.io>" --url "https://www.megam.io/" --description "Megam Vertice common which creates an user megam, group megam and base directories." ./usr/share/megam
