#!/bin/sh
cd nilavu/script
./d clean

cd ..

bundle update
bundle install
 
cd ..

pkgr package ./nilavu --user=megam --group=megam --maintainer="Thomas Alrin<thomasalrin@megam.io>, Raj Thilak <rajthilak@megam.co.in>, Kishorekumar Neelamegam<nkishore@megam.co.in>, Megam Systems <gomegam@megam.co.in>" --runner='upstart-1.5' --dependencies=megamcommon git-core curl bundler rake zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties ruby2.0 ruby2.0-dev wbritish wamerican --after-install=$PWD/postinst --before-install=$PWD/preinst --after-remove=$PWD/postrm --before-remove=$PWD/prerm --auto  --clean --name=$1 --version=$2 --iteration=1  --edge  --homepage="http://www.gomegam.com" --description="Nilavu - Web portal for Megam" --license="Apache" --home="/usr/share/megam"
