#!/bin/bash

mkdir -p /var/lib/megam/megamcib

set -e

. /usr/share/debconf/confmodule

chown megam:megam /var/run/megam/megamcib

chown megam:megam /var/log/megam/megamcib

systemctl start megamcib || echo "megamcib could not be started. Try manually with service megamcib start" >/dev/stdout

db_settitle megamcib/cibt

db_input critical megamcib/cibt || true
db_go

db_fset megamcib/cibt seen false
