#!/bin/sh

if [ -d "/usr/share/megam/megamdocker" ]; then
  rm -r /usr/share/megam/megamdocker
fi

if [ -d "/var/lib/megam/megamdocker" ]; then
  rm -r /var/lib/megam/megamdocker
fi

if [ -d "/var/log/megam/megamdocker" ]; then
  rm -r /var/log/megam/megamdocker
fi


ovs-vsctl del-br megdock
