#!/bin/sh

cd usr/share/megam/megamnilavu


bundle update

bundle install

cd ../../../..


fpm -s dir -t deb -n $1 -v $2 -d "megamcommon,git-core,curl,bundler,rake,zlib1g-dev,build-essential,libssl-dev,libreadline-dev,libyaml-dev, libsqlite3-dev,sqlite3,libxml2-dev,libxslt1-dev,libcurl4-openssl-dev,python-software-properties,ruby2.1,ruby2.1-dev,wbritish,wamerican" --before-upgrade ./preupgrd --after-upgrade ./postupgrd --before-install ./preinst --after-install ./postinst --before-remove ./prerm --deb-init ./etc/systemd/system/megamnilavu.service --license "Apache" --vendor "Megam Systems" --maintainer "Thomas Alrin<thomasalrin@megam.io>, Raj Thilak <rajthilak@megam.io>, Kishorekumar Neelamegam<nkishore@megam.io>, Yeshwanth Kumar <getyesh@megam.io>" --url "https://www.megam.io/" --description "Nilavu - Web(https://console.megam.io)" ./usr/share/megam/megamnilavu
