#!/bin/sh

mkdir -p /var/log/megam/megamnilavu

#set MEGAM_HOME for megamnilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/env.sh <<EOF
initctl set-env MEGAM_HOME='/var/lib/megam'
EOF

chmod 755 /var/lib/megam/env.sh

#ruby change 
rm /usr/bin/ruby
rm /usr/bin/gem
ln -s /usr/bin/ruby2.1 /usr/bin/ruby
ln -s /usr/bin/gem2.1 /usr/bin/gem

cp /usr/share/megam/megamnilavu/config/nilavu.yml /var/lib/megam/nilavu.yml

gem install bundler

cd /usr/share/megam/megamnilavu/
bundle install

#start megamnilavu

#initctl reload-configuration

cat >> /etc/systemd/system/megamnilavu.service << EOF
#Place the megam nilavu here /etc/systemd/system/megamnilavu.service
[Unit]
Description=Megam nilavu
After=network.target
After=runlevel2.target
After=runlevel3.target
After=runlevel4.target
After=runlevel5.target
[Service]
Type=forking
ExecStart=/usr/local/bin/bundle exec passenger start -a 127.0.0.1 -p 8080 -d -e production
ExecStopPost=/usr/local/bin/passenger stop --pid-file passenger.8080.pid
#WorkingDirectory=/usr/share/megam/megamnilavu
KillMode=mixed
EOF

systemctl enable megamnilavu.service 
systemctl start megamnilavu.service


