#!/bin/sh
cd vertice_gateway
cat > VERSION <<EOF
git_version=`git rev-parse HEAD`
git_branch=1.5
EOF
cp VERSION conf
cp db/base.cql conf

sbt clean
sbt dist:clean
sbt compile
sbt stage
sbt rpm:packageBin
