#!/bin/sh

cd usr/share/megam/verticenilavu

bundle update

bundle install

cd ../../../..

fpm -s dir -t deb -n $1 -v $2 -d "verticecommon,git-core,curl,bundler,rake,zlib1g-dev,build-essential,libssl-dev,libreadline-dev,libyaml-dev, libsqlite3-dev,sqlite3,libxml2-dev,libxslt1-dev,libcurl4-openssl-dev,python-software-properties,ruby2.0,ruby2.0-dev,wbritish,wamerican" --before-install ./preinst --after-install ./postinst --before-upgrade ./preupgrd --before-remove ./prerm --deb-upstart ./etc/init/verticenilavu --license "Apache" --vendor "Megam Systems" --maintainer "Thomas Alrin<thomasalrin@megam.io>, Raj Thilak <rajthilak@megam.io>, Kishorekumar Neelamegam<nkishore@megam.io>, Yeshwanth Kumar <getyesh@megam.io>" --url "https://www.megam.io/" --description "Nilavu - Web(https://console.megam.io)" ./usr/share/megam/verticenilavu
