#!/bin/sh

mkdir -p /var/log/megam/verticenilavu

#ruby change
rm /usr/local/bin/ruby
rm /usr/local/bin/gem
echo 'gem: --no-document' >> /usr/local/etc/gemrc
mkdir -p /src 
cd /src
git clone https://github.com/sstephenson/ruby-build.git
cd /src/ruby-build
./install.sh
cd /
 rm -rf /src/ruby-build
ruby-build 2.3.1 /usr/local

gem install bundler
rm -rf /usr/local/share/ri/2.3.0/system

#Cleanup file
rm -fr /usr/share/man
rm -fr /usr/share/doc
rm -fr /usr/local/share/doc
rm -fr /usr/local/share/ruby-build
rm -fr /tmp/*

#runit prepare
cd /
apt-get -y install runit monit socat
mkdir -p /etc/runit/1.d
apt-get clean
rm -f /etc/apt/apt.conf.d/40proxy
locale-gen en_US
apt-get install -y nodejs npm
npm install uglify-js -g
npm install svgo -g

cd /var/lib/megam
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/runit-1
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/runit-1.d-00-fix-var-logs
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/runit-1.d-cleanup-pids
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/runit-2
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/runit-3
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/boot
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/cron
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/rsyslog

mkdir -p /etc/runit/3.d
mv /var/lib/megam/runit-1 /etc/runit/1
mv /var/lib/megam/runit-1.d-cleanup-pids /etc/runit/1.d/cleanup-pids
mv /var/lib/megam/runit-1.d-00-fix-var-logs /etc/runit/1.d/00-fix-var-logs
mv /var/lib/megam/runit-2 /etc/runit/2
mv /var/lib/megam/runit-3 /etc/runit/3
mv /var/lib/megam/boot /sbin/boot
mkdir -p /etc/service/cron
mkdir -p /etc/service/rsyslog
mv /var/lib/megam/cron /etc/service/cron/run
mv /var/lib/megam/rsyslog /etc/service/rsyslog/run

### Install jmealloc

mkdir -p /jemalloc
cd /jemalloc
wget http://www.canonware.com/download/jemalloc/jemalloc-3.6.0.tar.bz2
tar -xjf jemalloc-3.6.0.tar.bz2
cd jemalloc-3.6.0
./configure
make
mv lib/libjemalloc.so.1 /usr/lib
cd /
rm -rf /jemalloc

###Install nginx
cd /var/lib/megam
wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/install-nginx
chmod 755 install-nginx
./install-nginx
mv install-nginx /tmp/install-nginx

##copy config file
cp /var/www/verticenilavu/config/nilavu.conf /var/lib/megam/nilavu.conf
cp /var/www/verticenilavu/config/site_settings.yml /var/lib/megam/site_settings.yml
cp /var/www/verticenilavu/config/regions.yml /var/lib/megam/regions.yml
cp /var/www/verticenilavu/config/nginx.conf /etc/nginx/conf.d/
mv /etc/nginx/conf.d/nginx.conf /etc/nginx/conf.d/nilavu.conf
rm /etc/nginx/sites-enabled/default
mkdir -p /var/nginx/cache

cat > /etc/runit/3.d/01-nginx <<EOF
#!/bin/bash
       sv stop nginx
EOF

chmod 755 /etc/runit/3.d/01-nginx

cat > /etc/runit/3.d/02-unicorn <<EOF
#!/bin/bash
       sv stop unicorn
EOF

chmod 755 /etc/runit/3.d/02-unicorn

mkdir -p /etc/service/unicorn
mkdir -p /etc/service/nginx
cp /etc/init.d/verticenilavu.service /etc/service/unicorn/
mv /etc/service/unicorn/verticenilavu.service /etc/service/unicorn/run
chmod 755 /etc/service/unicorn/run

cat > /etc/service/nginx/run <<EOF
#!/bin/sh
        exec 2>&1
        exec /usr/sbin/nginx
EOF
chmod 755 /etc/service/nginx/run


cd /var/www/verticenilavu/
bundle install --deployment --without test --without development
RAILS_ENV=production bundle exec rake assets:precompile

sv start unicorn
sv start nginx
