#!/bin/sh

mkdir -p /var/log/megam/verticenilavu

#set MEGAM_HOME for verticenilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/env.sh <<EOF
initctl set-env MEGAM_HOME='/var/lib/megam'
EOF

chmod 755 /var/lib/megam/env.sh

#ruby change
rm /usr/bin/ruby
rm /usr/bin/gem
ln -s /usr/bin/ruby2.0 /usr/bin/ruby
ln -s /usr/bin/gem2.0 /usr/bin/gem

cp /usr/share/megam/verticenilavu/config/nilavu.yml /var/lib/megam/nilavu.yml

gem install bundler

cd /usr/share/megam/verticenilavu/

bundle update

start verticenilavu

initctl reload-configuration
