#!/bin/sh

cd pysnowflake

mkdir -p ../usr/share/megam/snowflake/bin

cp -r ./src ../usr/share/megam/snowflake/bin

cd ..

fpm -s dir -t rpm -n $1 -v $2 -d "verticecommon,python,python-pip" --before-install ./preinst --after-install ./postinst --before-remove ./prerm  --after-remove ./postrm --rpm-init ./etc/systemd/system/snowflake.service --license "Apache" --vendor "Megam Systems" --maintainer "<info@megam.io>" --url "https://www.megam.io" --description "Python based unique id generator server based on Twitters snowflake. source : https://github.com/erans/pysnowflake.git" ./usr/share/megam/snowflake/bin

