#!/bin/sh

cd megam_gateway
sed -i "s/version := .*/version := \"0.9\"/" build.sbt
/home/megam/bin/sbt clean
/home/megam/bin/sbt dist:clean
/home/megam/bin/sbt compile
/home/megam/bin/sbt stage
/home/megam/bin/sbt debian:package-bin
