require "rake"
require "../version.rb"
require "./config.rb"
puts ">> ------------- [#{MegamPkg::Ger::CONFIG[:name]} #{MegamPkg::Ger::VERSION}]"

megger = MegamPkg::Ger.new

nix_dir="nix"
build_dir ="build"

task :default => :trusty

task :clean do
  rm_rf build_dir
end

task :initnix do
  mkdir_p build_dir
  mkdir_p megger.build_halwa

  #Rake::FileList[nix_dir +"/**"].each do |f|
   #target = File.join megger.build_halwa,  File.basename(f)
    #cp_r f, target
 # end
end

#this overrides the nix/ stuff with halwa specific stuff.
task :nix => [:initnix] do
  Rake::FileList["#{megger.halwa}" +"/**"].each do |f|
    target = File.join megger.build_halwa,  File.basename(f)
    cp_r f, target
  end if File.exists?(megger.halwa)
 
  Dir.chdir megger.build_halwa
mkdir_p "usr/share/megam"  
Rake::Task[:clone].invoke
  system './g', MegamPkg::Ger::CONFIG[:name], MegamPkg::Ger::VERSION
end

#i know this repeating, but this to partition the supported os just we don't have to do typechecking.
# rake trusty
# rake precise
# rake centos7
# rake jessie
task :trusty   do
  megger.halwa="trusty"
  megger.build_halwa="build/trusty"
  Rake::Task[:nix].invoke
end

task :precise   do
  megger.halwa ="precise"
  megger.build_halwa="build/precise"
  Rake::Task[:nix].invoke
end

task :centos7 do
  megger.halwa ="centos7"
  megger.build_halwa="build/centos7"
  Rake::Task[:nix].invoke
end

task :jessie do
  megger.halwa ="jessie"
  megger.build_halwa="build/jessie"
  Rake::Task[:nix].invoke
end

task :clone do
  if !File.exists? 'nilavu/'
   Dir.chdir "usr/share/megam"
   system "git clone -b #{MegamPkg::Ger::CONFIG[:branch]} https://github.com/megamsys/nilavu.git megamnilavu"
 end
Dir.chdir '../../..'
end
