#!/bin/bash
mkdir -p ./usr/share/megam/megamgulpd/bin

cd gulp/src/github.com/megamsys/gulp

#if the upstream, master remote is not set, then the builds will not go thru.
git remote add master https://github.com/megamsys/gulp.git

make build

cp -rf ./conf/ ../../../../../usr/share/megam/megamgulpd

cp gulpd ../../../../../usr/share/megam/megamgulpd/bin

cd ../../../../../


fpm -s dir -t rpm -n $1 -v $2 -d "megamcommon" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --rpm-init ./etc/systemd/system/megamgulpd.service --license "Apache" --vendor "Megam Systems" --maintainer "<thomasalrin@megam.io>" --url "https://www.megam.io" --description "Megam node daemon that controls the lifecycle of an app" ./usr/share/megam/megamgulpd
