#!/bin/bash

mkdir -p /var/lib/megam/megamgulpd

echo "Megamgulpd installed successfully"
#systemctl start megamgulpd.service || echo "megamgulpd could not be started. Try manually with service megamgulpd start" >/dev/stdout

