#!/bin/bash

mkdir -p ./usr/share/megam/cadvisor/bin

wget https://s3.amazonaws.com/megam/cadvisor
chmod 755 cadvisor

cp -rf ../../jessie/etc/systemd/system/cadvisor.service ./usr/share/megam/cadvisor
cp cadvisor ./usr/share/megam/cadvisor/bin

fpm -s dir -t deb -n $1 -v $2 -d "verticecommon, unzip" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm  --deb-init ./etc/systemd/system/cadvisor.service --license "Apache" --vendor "Megam Systems" --maintainer "Megam Maintainer info@megam.io" --url "https://www.megam.io/" --description "Analyzes resource usage and performance characteristics of running containers/machine." ./usr/share/megam/cadvisor
