#!/bin/bash

mkdir -p ./usr/share/megam/megamswarm/bin

cd megamswarm/src/github.com/docker/swarm

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/megamsys/swarm.git

make build

cp swarm ../../../../../usr/share/megam/megamswarm/bin

cd ../../../../../

fpm -s dir -t deb -n $1 -v $2 -d "verticecommon" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --deb-upstart ./etc/init/megamswarm --license "Apache" --vendor "Megam Systems" --maintainer "<getyesh@megam.io>, <rajthilak@megam.io>" --url "https://www.megam.io/" --description "The docker cluster scheduler on baremetal for multiple hosts" ./usr/share/megam/megamswarm
