#!/bin/bash

mkdir -p ./usr/share/megam/megamswarm/bin

cd megamswarm/src/github.com/docker/swarm

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/megamsys/swarm.git

make build

cp swarm ../../../../../usr/share/megam/megamswarm/bin

cd ../../../../../

fpm -s dir -t deb  -p "$MEGAM_HOME"  -f  --iteration $3 -n $1 -v $2 -d "verticecommon" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --deb-upstart ./etc/init/megamswarm --license "Apache V2" --vendor "Megam Systems" --category "infrastructure" --maintainer "Megam Maintainer info@megam.io" --url "http://docs.megam.io/docs/megam_docker" --description "The swarm uses Dockers swarm which enables a bunch of hosts in your datacenter
   to be managed and containerized from Megam Vertice. This is connected to the Vertice gateway (API server) only
   .
   This provides the features of swarm allowing orchestration and management of containers.
   .
   This package contains a golang based server for Megam Vertice (Docker support)" ./usr/share/megam/megamswarm
