#!/bin/bash


DOCKER_PATH=/var/lib/docker/containers/*
DOCK_PATH=/var/lib/docker/containers/


HEKA_READ_PATH=/var/lib/megam/megamd/

CONFIG_FILE="config.json"
JSON_SUFFIX="-json.log"



function jsonval() {

KEY=$1
num=$2


awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}


function main() {
for dir in $DOCKER_PATH
  do
  dir=${dir%*/}
  CONT=${dir##*/} 
  CONF_PATH=$DOCK_PATH$CONT/$CONFIG_FILE
  LOG=$CONT$JSON_SUFFIX   
  chmod 755 $CONF_PATH    
 myName=$(cat $CONF_PATH | jsonval Name 1) 
        HEKA_DIR=$HEKA_READ_PATH$myName
   mkdir $HEKA_DIR
   ln -s $LOG $HEKA_DIR/$myName    

done
}

main
  
