#!/bin/bash

if pgrep docker
  then
  echo "###############################################################"
  echo "# Warning: Docker shouldn't be installed in the swarmmaster.  #"
  echo "#          Proceeding by stopping docker......                #"
  echo "###############################################################"
  service docker stop
fi

mkdir -p /var/lib/megam/megamswarm
mkdir -p /var/log/megam/megamswarm
