#!/bin/bash

mkdir -p ./usr/share/megam/megamd/bin

cd megamd/src/github.com/megamsys/megamd

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/megamd.git

make build

cp -rf ./conf/ ../../../../../usr/share/megam/megamd
cp megamd ../../../../../usr/share/megam/megamd/bin

cd ../../../../../

cp riakstash ./usr/share/megam/megamd/bin
cp riakstash.cron.d ./usr/share/megam/megamd/bin

fpm -s dir -t deb -n $1 -v $2 -d "megamcommon, unzip" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --deb-upstart ./etc/init/megamd --license "Apache" --vendor "Megam Systems" --maintainer "<rajthilak@megam.io>" --url "https://www.megam.io/" --description "The engine for Megam" ./usr/share/megam/megamd
