#!/bin/bash

mkdir -p /var/lib/megam/megamd

initctl reload-configuration

cp /usr/share/megam/megamd/bin/link_container_logs /var/lib/megam/megamd

chmod +x /var/lib/megam/megamd/link_container_logs

crontab  /usr/share/megam/megamd/bin/link_container_logs.cron.d

rm /usr/share/megam/megamd/bin/link_container_logs.cron.d

service megamd start || echo "megamd could not be started. Try manually with service megamd start"
