require "rake"
require "../../version.rb"
require "./config.rb"
puts ">> ------------- [#{MegamPkg::Ger::CONFIG[:name]} #{MegamPkg::Ger::VERSION}]"
task :default => :precise

build_dir ="build"
trusty_dir ="trusty"
build_trusty_dir ="build/trusty"

precise_dir ="precise"
build_precise_dir ="build/precise"

task :clean do
  rm_rf build_trusty_dir
  rm_rf build_dir
  rm_rf build_precise_dir
end


task :trusty => [:inittrusty_setup, :clone] do
  system './g', MegamPkg::Ger::CONFIG[:name], MegamPkg::Ger::VERSION
end

task :inittrusty_setup do
  mkdir_p build_dir
  mkdir_p build_trusty_dir
  Rake::FileList[trusty_dir +"/**"].each do |f|
    target = File.join build_trusty_dir,  File.basename(f)
    cp f, target
  end
  Dir.chdir build_trusty_dir
end

task :initprecise_setup do
  mkdir_p build_dir
  mkdir_p build_precise_dir
  Rake::FileList[precise_dir +"/**"].each do |f|
    target = File.join build_precise_dir,  File.basename(f)
    cp f, target
  end
  Dir.chdir build_precise_dir
end

task :precise => [:initprecise_setup, :clone] do
  system './ruby-2.0.0-build'
  system './g', MegamPkg::Ger::CONFIG[:name], MegamPkg::Ger::VERSION

end


task :clone do
  if !File.exists? 'nilavu/'
   system "git clone -b #{MegamPkg::Ger::CONFIG[:branch]} https://github.com/megamsys/nilavu.git"
 end
end

task :copydeb do
  if !File.exists? '*.deb'
   cp './nilavu/*.deb' '../../../'
  end
end
