#!/bin/sh

cd usr/share/megam/verticenilavu

bundle update

bundle install

cd ../../../..

fpm -s dir -t rpm -n $1 -v $2 -d "verticecommon,git-core,curl,rake,zlib-devel,zlib,readline-devel,libyaml-devel,libxml2-devel,openssl-devel,ruby,ruby-devel" --before-install ./preinst --after-install ./postinst --before-upgrade ./preupgrd --before-remove ./prerm --rpm-init ./etc/etc/systemd/system/verticenilavu.service --license "Apache" --vendor "Megam Systems" --maintainer "Thomas Alrin<thomasalrin@megam.io>, Raj Thilak <rajthilak@megam.io>, Kishorekumar Neelamegam<nkishore@megam.io>, Yeshwanth Kumar <getyesh@megam.io>" --url "https://www.megam.io/" --description "Nilavu - Web(https://console.megam.io)" ./usr/share/megam/verticenilavu
