#!/bin/bash

mkdir -p /var/lib/megam/vertice

cp /usr/share/megam/vertice/conf/vertice.conf /var/lib/megam/vertice/vertice.conf

cat >> /var/lib/megam/env.sh << EOF
MEGAM_HOME='/var/lib/megam/'
EOF

chmod 0755 /var/lib/megam/env.sh

systemctl enable vertice.service

systemctl start vertice.service
