#!/bin/sh

if [ -d "/usr/share/megam/vertice" ]; then
  rm -r /usr/share/megam/vertice
fi

if [ -d "/var/lib/megam/vertice" ]; then
  rm -r /var/lib/megam/vertice
fi

if [ -d "/var/run/megam/vertice" ]; then
  rm -r /var/run/megam/vertice
fi

if [ -d "/var/log/megam/vertice" ]; then
  rm -r /var/log/megam/vertice
fi
