#!/bin/bash

cp /etc/init.d/verticegulpd.service /etc/systemd/system/

cat > //var/lib/megam/env.sh <<EOF
MEGAM_HOME='/var/lib/megam'
HOST='localhost'
EOF

chmod 755 /var/lib/megam/env.sh
mkdir -p /var/lib/megam/verticegulpd /var/lib/megam/gulp/

cp /usr/share/megam/verticegulpd/conf/gulpd.conf /var/lib/megam/gulp

systemctl enable verticegulpd.service
systemctl start verticegulpd.service
