require "rake"
require "../version.rb"
require "./config.rb"
puts ">> ------------- [#{MegamPkg::Ger::CONFIG[:name]} #{MegamPkg::Ger::VERSION}]"

megger = MegamPkg::Ger.new

nix_dir="nix"
build_dir ="build"

task :default => :trusty

task :clean do
  rm_rf build_dir
end

task :initnix do
  mkdir_p build_dir
  mkdir_p megger.build_halwa

  #Rake::FileList[nix_dir +"/**"].each do |f|
   # target = File.join megger.build_halwa,  File.basename(f)
    #cp_r f, target
  #end
end

#this overrides the nix/ stuff with halwa specific stuff.
task :nix => [:initnix] do
  Rake::FileList["#{megger.halwa}" +"/**"].each do |f|
    target = File.join megger.build_halwa,  File.basename(f)
    cp_r f, target
  end if File.exists?(megger.halwa)

  Dir.chdir megger.build_halwa
  #mkdir_p "megamd/src/github.com/megamsys"
  Rake::Task[:clone].invoke
#system './g_heka', MegamPkg::Ger::CONFIG[:heka_name], MegamPkg::Ger::VERSION  
system './g_tap', MegamPkg::Ger::CONFIG[:tap_name], MegamPkg::Ger::VERSION
end

#i know this repeating, but this to partition the supported os just we don't have to do typechecking.
# rake trusty
# rake precise
# rake centos7
# rake jessie
task :trusty   do
  megger.halwa="nix"
  megger.build_halwa="build/trusty"
  Rake::Task[:nix].invoke
end

task :precise   do
  megger.halwa ="precise"
  megger.build_halwa="build/precise"
  Rake::Task[:nix].invoke
end

task :centos7 do
  megger.halwa ="centos7"
  megger.build_halwa="build/centos7"
  Rake::Task[:nix].invoke
end

task :jessie do
  megger.halwa ="jessie"
  megger.build_halwa="build/jessie"
  Rake::Task[:nix].invoke
end


task :clone do
  if !File.exists? 'heka/'
   #system "git clone https://github.com/megamsys/heka.git"
 end
  if !File.exists? 'tap/'
   system "git clone https://github.com/megamsys/tap.git"
 end
end

