#!/bin/sh
#!/bin/sh
if [ -d "/usr/share/megam/snowflake" ]; then
  rm -r /usr/share/megam/snowflake
fi

if [ -d "/var/run/megam/snowflake" ]; then
  rm -r /var/run/megam/snowflake
fi

if [ -d "/var/log/megam/snowflake" ]; then
  rm -r /var/log/megam/snowflake
fi
