#!/bin/bash
mkdir -p ./usr/share/megam/verticegulpd/bin


cd gulp/src/github.com/megamsys/gulp

#if the upstream, master remote is not set, then the builds will not go thru.
git remote add master https://github.com/megamsys/gulp.git

make build

cp -rf ./conf/ ../../../../../usr/share/megam/verticegulpd
cp gulpd ../../../../../usr/share/megam/verticegulpd/bin

cd ../../../../../

fpm -s dir -t deb -n $1 -v $2 -d "verticecommon" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --deb-init ./etc/systemd/system/verticegulpd.service --license "Apache" --vendor "Megam Systems" --maintainer "<thomasalrin@megam.io>" --url "https://www.megam.io/" --description "Megam Vertice agent that runs inside baremetal or vm" ./usr/share/megam/verticegulpd
