#!/bin/bash

mkdir -p ./usr/share/megam/vertice/bin

cd vertice/src/github.com/megamsys/vertice

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/vertice.git

make build

cp -rf ./conf/ ../../../../../usr/share/megam/vertice
cp vertice ../../../../../usr/share/megam/vertice/bin

cd ../../../../../

cp riakstash ./usr/share/megam/vertice/bin
cp riakstash.cron.d ./usr/share/megam/vertice/bin

fpm -s dir -t deb -n $1 -v $2 -d "verticecommon, unzip" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --deb-init ./etc/systemd/system/vertice.service --license "Apache" --vendor "Megam Systems" --maintainer "<info@megam.io>" --url "https://www.megam.io/" --description "The engine for Megam" ./usr/share/megam/vertice
