#!/bin/bash

mkdir -p /var/lib/megam/vertice

#initctl reload-configuration

cp /usr/share/megam/vertice/conf/vertice.conf /var/lib/megam/vertice/vertice.conf

#service vertice start || echo "vertice could not be started. Try manually with service vertice start"

mv /etc/init.d/vertice.service /etc/systemd/system/

cat >> /var/lib/megam/env.sh << EOF
MEGAM_HOME='/var/lib/megam/'
EOF

chmod 0755 /var/lib/megam/env.sh

systemctl enable vertice.service
systemctl start vertice.service
