#!/bin/sh

TMP_BUILD_HOME=./usr/share/megam/$1

mkdir -p $TMP_BUILD_HOME
mkdir -p $TMP_BUILD_HOME/log

#just copy what you want.
cp -r ./nilavu/config.ru $TMP_BUILD_HOME
cp -r ./nilavu/Gemfile $TMP_BUILD_HOME
cp -r ./nilavu/Gemfile.lock $TMP_BUILD_HOME
cp -r ./nilavu/g $TMP_BUILD_HOME
cp -r ./nilavu/License $TMP_BUILD_HOME
cp -r ./nilavu/Rakefile $TMP_BUILD_HOME
cp -r ./nilavu/README.md $TMP_BUILD_HOME

cp -r ./nilavu/app $TMP_BUILD_HOME
cp -r ./nilavu/config $TMP_BUILD_HOME
cp -r ./nilavu/public $TMP_BUILD_HOME
cp -r ./nilavu/vendor $TMP_BUILD_HOME

rm -rf ./nilavu


cd $TMP_BUILD_HOME

export MEGAM_HOME="$PWD/config"

bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j2 --deployment

rake assets:clean
rake tmp:clear
rake assets:precompile RAILS_ENV=production

fpm -s dir -t deb -n $1 -v $2 --after-install ./postinst --after-remove ./postrm --license "Apache" --vendor "Megam Systems" --maintainer="Thomas Alrin<thomasalrin@megam.io>, Raj Thilak <rajthilak@megam.io>, Kishorekumar Neelamegam<nkishore@megam.io>, Yeshwanth kumar <getyesh@megam.io>, Megam Systems <info@megam.io>" --url "https://www.megam.io/" --deb-upstart ./etc/init/megamnilavu.conf --description "Megam Nilavu - Web as (https://console.megam.io)" $TMP_BUILD_HOME
