#!/bin/sh
cd nilavu
rake assets:clean
rake tmp:clear


bundle update
bundle install

cd ..


pkgr package ./nilavu -maintainer="Thomas Alrin<thomasalrin@megam.io>, Raj Thilak <rajthilak@megam.io>, Kishorekumar Neelamegam<nkishore@megam.io>, Megam Systems <info@megam.io>" --runner='upstart-1.5' --dependencies=megamcommon git-core curl bundler rake zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties wbritish wamerican --after-install=$PWD/postinst --before-install=$PWD/preinst --after-remove=$PWD/postrm --before-remove=$PWD/prerm --auto  --clean --name=$1 --version=$2 --iteration=1  --edge  --homepage="https://www.megam.io/" --description="Nilavu - Web portal for Megam" --license="Apache" --home="/usr/share/megam"
