#!/bin/sh

mkdir -p /var/log/megam/megamnilavu

#set MEGAM_HOME for megamnilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/env.sh <<EOF
initctl set-env MEGAM_HOME='/var/lib/megam'
EOF

chmod 755 /var/lib/megam/env.sh

gem install passenger

cp /usr/share/megam/megamnilavu/config/nilavu.yml /var/lib/megam/nilavu.yml

echo "starting megamnilavu..."
sudo start megamnilavu
echo "started"

initctl reload-configuration
