#!/bin/sh

ln -sf /usr/bin/ruby2.0 /usr/bin/ruby
ln -sf /usr/bin/gem2.0 /usr/bin/gem

mkdir /etc/unicorn
mkdir -p /var/log/megam/megamnilavu
mkdir -p /var/run/megam/megamnilavu

#chown megam:megam /var/run/megam/megamnilavu

#chown megam:megam /var/log/megam/megamnilavu


cat > /etc/unicorn/nilavu.rb <<EOF

##
# Unicorn config at /etc/unicorn/nilavu.rb
##

# What ports/sockets to listen on, and what options for them.
listen "8080", :tcp_nodelay => true, :backlog => 100

working_directory '/usr/share/megam/megamnilavu'

pid "/var/run/megam/megamnilavu/nilavu.pid"

stdout_path "/var/log/megam/megamnilavu/nilavu_out.log"
stderr_path "/var/log/megam/megamnilavu/nilavu_err.log"

# What the timeout for killing busy workers is, in seconds
timeout 60

# Whether the app should be pre-loaded
preload_app false

# How many worker processes
worker_processes 8


# Run forked children as specified user/group
user "megam", "megam"


# What to do before we fork a worker
before_fork do |server, worker|
  sleep 1
end

EOF

#set MEGAM_HOME for megamnilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/env.sh <<EOF
initctl set-env MEGAM_HOME='/var/lib/megam'             
EOF

chmod 755 /var/lib/megam/env.sh

cat > //etc/init/megamnilavu.conf <<EOF
# Configuration Upstart file for Nilavu
description "Upstart script for nilavu"

start on (local-filesystems)
stop on runlevel [!12345]


pre-start script
cd /var/lib/megam
./env.sh
end script


respawn

exec start-stop-daemon --start --chdir "/usr/share/megam/megamnilavu/" --exec /usr/bin/bundle exec unicorn_rails -- -E production -c "/etc/unicorn/nilavu.rb"
EOF

cat > //usr/share/megam/megamnilavu/production.log <<EOF
test log
EOF

chmod 666 /usr/share/megam/megamnilavu/production.log

chown -R megam:megam /usr/share/megam/megamnilavu

cat > //var/lib/megam/nilavu.yml <<EOF                                  #Common yml

monitor:
  metric_source: ganglia
  host: ganglia_host
  base_url: http://monitor.megam.co.in/ganglia
  cluster: megampaas

storage:
  type: local
  aws_access_key: AWS_ACCCESS_KEY
  aws_secret_key: AWS_SECRET_KEY
  cross_cloud: cloud_keys
  cloud_tool: cloudrecipes
  server_url: https://s3-ap-southeast-1.amazonaws.com

api:
  host: localhost
  pub_key: megamgateway_pub.crt
  private_key: megamgateway.key

#if db and production are start from begining of the line it assumes as two inner hashes 
#{"db"=>nil, "production"=>{"adapter"=>"sqlite3"}}
#db:
#  production:
#        adapter: sqlite3
#        database: db/cocdb
#        pool: 5
#        timeout: 5000
EOF

cd /usr/share/megam/megamnilavu
gem install rake

export MEGAM_HOME=/var/lib/megam                        #To have DB under megam_home

echo "setting up database"
rake db:migrate
rake db:seed



[ -d /var/lib/megam/db ] && chown -R megam:megam /var/lib/megam/db 
[ -d /usr/share/megam/megamnilavu/db ] && chown -R megam:megam /usr/share/megam/megamnilavu/db

echo "starting megamnilavu"
sudo start megamnilavu
echo "started"

initctl reload-configuration


