#!/bin/sh
cd nilavu/script
./d clean

cd ..

mkdir -p ./usr/share/megam

cd ..

bundle update
bundle install 


pkgr package ./nilavu --user=megam --group=megam --maintainer="Thomas Alrin<alrin@megam.co.in>, Raj Thilak <rajthilak@megam.co.in>, Kishorekumar Neelamegam<nkishore@megam.co.in>, Megam Systems <gomegam@megam.co.in>" --runner='upstart-1.5' --dependencies=megamcommon git-core curl bundler rake build-essential readline-devel zlib-devel libssl-dev libreadline-dev libyaml-devel libffi-devel libxml2-devel openssl-devel make bzip2 autoconf automake libtool bison iconv-devel libxslt-dev libcurl4-devel ruby ruby-devel words --after-install=./postinst --before-install=./preinst --after-remove=./postrm --before-remove=./prerm --auto  --clean --name=$1 --version=$2 --iteration=1  --edge  --homepage="http://www.gomegam.com" --description="Nilavu - Web portal for Megam" --license="Apache" 
