#!/bin/sh

ln -sf /usr/bin/ruby2.0 /usr/bin/ruby
ln -sf /usr/bin/gem2.0 /usr/bin/gem

mkdir /etc/unicorn
mkdir -p /var/log/megam/megamnilavu
mkdir -p /var/run/megam/megamnilavu

#chown megam:megam /var/run/megam/megamnilavu

#chown megam:megam /var/log/megam/megamnilavu


cat > /etc/unicorn/nilavu.rb <<EOF

##
# Unicorn config at /etc/unicorn/nilavu.rb
##

# What ports/sockets to listen on, and what options for them.
listen "8080", :tcp_nodelay => true, :backlog => 100

working_directory '/usr/share/megam/megamnilavu'

stdout_path "/var/log/megam/megamnilavu/nilavu_out.log"
stderr_path "/var/log/megam/megamnilavu/nilavu_err.log"

# What the timeout for killing busy workers is, in seconds
timeout 60

# Whether the app should be pre-loaded
preload_app false

# How many worker processes
worker_processes 8

# What to do before we fork a worker
before_fork do |server, worker|
  sleep 1
end

EOF

#set MEGAM_HOME for megamnilavu    NOTFOR THE WHOLE SYSTEM(we can't access by echo $MEGAM_HOME)
cat > //var/lib/megam/megamnilavu.env <<EOF
MEGAM_HOME='/var/lib/megam'           
EOF

cat > //etc/systemd/system/megamnilavu.service <<EOF
[Unit]
Description=Upstart script for nilavu
After=network.target
After=runlevel2.target
After=runlevel3.target
After=runlevel4.target
After=runlevel5.target
[Service]
EnvironmentFile='/var/lib/megam/megamnilavu.env' 
ExecStartPre=[ -d /var/run/megam/megamnilavu ] || mkdir -p /var/run/megam/megamnilavu
ExecStartPre=[ -d /var/log/megam/megamnilavu ] || mkdir -p /var/log/megam/megamnilavu
ExecStart=start-stop-daemon --start --chdir "/usr/share/megam/megamnilavu/" --exec /usr/bin/bundle exec unicorn_rails -- -E production -c "/etc/unicorn/nilavu.rb"
ExecStartPost=`status megamnilavu | egrep -oi '([0-9]+)$' | head -n1` > /var/run/megam/megamnilavu/megamnilavu.pid
ExecStopPost=rm /var/run/megam/megamnilavu/megamnilavu.pid | echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) megamnilavu Stopping" >> /var/log/megam/megamnilavu/megamnilavu.log
#ExecStop=runlevel0.target
#ExecStop=runlevel1.target
#ExecStop=runlevel6.target
#KillMode=mixed

EOF

chmod 755 /var/lib/megam/megamnilavu.env


cat > //usr/share/megam/megamnilavu/production.log <<EOF
test log
EOF

chmod 666 /usr/share/megam/megamnilavu/production.log

#chown -R megam:megam /usr/share/megam/megamnilavu

cat > //var/lib/megam/nilavu.yml <<EOF                                  #Common yml

api:
  host: localhost
  #host: api.megam.co
  scheme: http
  pub_key: megamgateway_pub.crt
  private_key: megamgateway.key

storage:
  type: riak
  #server_url: 192.168.2.6
  server_url: localhost
  cloud_tool_bucket: cloudtools
  cloud_keys_bucket: cloudaccesskeys
  ssh_files_bucket: sshfiles
  #type :s3
  #server_url: https://s3-ap-southeast-1.amazonaws.com

tap:
  host: localhost
  port: 7000

varai:
  host: localhost
  port: 1880

auth:
  fb_client_id:
  fb_secret_key:
  twitter_client_id:
  twitter_secret_key:
  github_client_id:
  github_secret_key:
  assembla_client_id:
  assembla_secret_key:
  google_client_id: 394446952494-vajon1t747d507rka21nm8ls96qg5p4u.apps.googleusercontent.com
  google_secret_key: WNd7iGxEQsC8HQGEFgMiXnXb

monitor:
  metric_source: ganglia
  host: ganglia_host
  base_url: http://monitor.megam.co.in/ganglia
  cluster: megampaas

EOF

cd /usr/share/megam/megamnilavu
gem install rake


echo "starting megamnilavu" >/dev/stdout
sudo systemctl start megamnilavu.service
echo "started" >/dev/stdout

systemctl reload megamnilavu.service


