#!/bin/sh
mkdir -p ./usr/share/megam/nsqd/bin

wget -r -c -O nsqd.tar.gz https://s3.amazonaws.com/bitly-downloads/nsq/nsq-0.3.6.linux-amd64.go1.5.1.tar.gz

tar -xvf nsq.tar.gz -C ./usr/share/megam/nsq --strip-components=1 && rm nsq.tar.gz

fpm -s dir -t deb -n $1 -v $2 --before-install ./preinst --after-install ./postinst --before-remove ./prerm --deb-upstart ./etc/init/nsqd --license "Apache" --vendor "Megam Systems" --maintainer "<info@megam.io>" --url "https://www.megam.io" --description "Nsq messaging for Megam Oja" ./usr/share/megam/nsqd/bin
