#!/bin/sh

while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
		[ "$Mask" = "00000000" ] && \
		interface="$Iface" && \
		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
		ipaddr=${ipaddr#* inet } && \
		ipaddr=${ipaddr%%/*} && \
		break
done < /proc/net/route


cat > //var/lib/megam/env.sh <<EOF
MEGAM_NSLOOKUPD_IP="$ipaddr"
EOF



initctl reload-configuration
echo "nsqd not yet started. Try manually 'service nsqd start'"
