#!/bin/sh

set -e

MEGAMHOME=/var/lib/megam
MEGAM_INSTALLHOME=/usr/share/megam
MEGAM_GROUP=megam
MEGAM_USER=megam

mkdir -p /usr/share/megam
mkdir -p /var/log/megam
mkdir -p /var/run/megam

create_megamgroup() {
    if ! getent group $MEGAM_GROUP > /dev/null 2>&1; then
        groupadd --system $MEGAM_GROUP
    fi
}

create_megamuser() {
         mkdir -p $MEGAMHOME
    if ! getent passwd $MEGAM_USER > /dev/null 2>&1; then
	
        adduser -r -g $MEGAM_GROUP -d $MEGAMHOME -s /bin/bash $MEGAM_USER
    else
        MEGAMHOME=`getent passwd $MEGAM_USER | cut -f6 -d:`
        # Renable user (give him a shell)
        usermod --shell /bin/bash $MEGAM_USER
        # Make sure MEGAMHOME exists, might have been removed on previous purge
        mkdir -p $MEGAMHOME
    fi
}
#echo "Error msg --> Something may be wrong!" > /dev/stderr
#echo "Error msg --> $1" > /dev/stderr


if [ "$1" = 1 ]; then
    create_megamgroup
    create_megamuser
   
    if ! [ -d "$MEGAM_INSTALLHOME" ]; then
        mkdir "$MEGAM_INSTALLHOME"
    fi
fi
