#!/bin/sh

chown megam:megam /var/lib/megam/megamgogs

chown -R  megam:megam /var/lib/megam/megamgogs/repos

chown megam:megam /usr/share/megam/megamgogs

chown -R megam:megam /usr/share/megam/megamgogs

initctl reload-configuration

service megamgogs start || echo "megamgogs could not be started. Try manually with service megamgogs start"
