#!/bin/sh


mkdir -p ./usr/share/megam

fpm -s dir -t rpm -n megamcommon -v 0.1 --after-install ./postinst --after-remove ./postrm --license "Apache" --vendor "Megam Systems" --maintainer "<rajthilak@megam.io>" --url "https://www.megam.io" --description "Megam common an empty package which just creates an user megam and group megam." ./usr/share/megam

