#!/bin/bash

mkdir -p ./usr/share/megam/megdc/bin

mkdir -p ./usr/share/megam/megdc/conf/trusty/opennebula/

cd megdc/src/github.com/megamsys/megdc

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/megdc.git

make

cp megdc ../../../../../usr/share/megam/megdc/bin

cp conf/install_gems ../../../../../usr/share/megam/megdc/conf/
cp conf/megdc.conf ../../../../../usr/share/megam/megdc/conf

cd ../../../../../

fpm -s dir -t deb -p "$MEGAM_HOME"  -f  --iteration $3 -n $1 -v $2 --before-install ./preinst --after-install ./postinst   --after-remove ./postrm --license "Apache V2" --vendor "Megam Systems" --category "infrastructure" --maintainer "Megam Maintainer info@megam.io" --url "http://docs.megam.io" --description "Description: command line which sets up OpenNebula, Ceph/LVM, Megam Vertice
OpenNebula is an open source virtual infrastructure engine. Ceph is an
open source unified cloud storage. Megam Vertice is an opensource platform
as service engine.
.
Vertice ONE (OpenNebula) extends the benefits of virtualization platforms from a
single physical resource to a pool of resources, decoupling the server not
only from the physical infrastructure but also from the physical location.
.
This package contains Megdc command line which make your datacenter cloud using
open source." ./usr/share/megam/megdc
