#!/bin/bash

mkdir -p ./usr/share/megam/megdc/bin

mkdir -p ./usr/share/megam/megdc/conf/trusty/opennebula/

cd megdc/src/github.com/megamsys/megdc

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/megdc.git

make

cp megdc ../../../../../usr/share/megam/megdc/bin

cp conf/install_gems ../../../../../usr/share/megam/megdc/conf/

cd ../../../../../

fpm -s dir -t deb -n $1 -v $2 --before-install ./preinst --after-install ./postinst   --after-remove ./postrm --license "Apache" --vendor "Megam Systems" --maintainer "<info@megam.io>" --url "https://www.megam.io/" --description "A CLI based megam datacenter management interface" ./usr/share/megam/megdc
