#!/bin/sh

while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
		[ "$Mask" = "00000000" ] && \
		interface="$Iface" && \
		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
		ipaddr=${ipaddr#* inet } && \
		ipaddr=${ipaddr%%/*} && \
		break
done < /proc/net/route

mv /usr/share/megam/nsqd/nsqlookupd /etc/systemd/system/nsqlookupd.service
mv /usr/share/megam/nsqd/nsqadmin  /etc/systemd/system/nsqadmin.service
chmod 755 /etc/systemd/system/nsqlookupd.service
chmod 755 /etc/systemd/system/nsqadmin.service
mkdir /var/lib/megam/nsqd
mv /etc/init.d/nsqd /etc/systemd/system/nsqd.service
sed -i 's/lookupd-tcp-address=localhost:4160/lookupd-tcp-address='$ipaddr':4160/g' /etc/systemd/system/nsqd.service
sed -i 's/lookupd-http-address=localhost:4161/lookupd-http-address='$ipaddr':4161/g' /etc/systemd/system/nsqadmin.service

#initctl reload-configuration
echo "nsqd not yet started. Try manually 'service nsqd start or systemctl nsqd start'"
