#!/bin/bash

set -e

chown megam:megam /var/run/megam/megamcib

chown megam:megam /var/log/megam/megamcib

initctl reload-configuration

service megamcib start || echo "megamcib could not be started. Try manually with service megamcib start"

# Source debconf library
. /usr/share/debconf/confmodule

# Set title for the dialog
db_settitle cib-config/title

db_input critical cib-config/text

db_go
