#!/bin/sh
fpm -s dir -t deb -n $1 -v $2 -d "ganglia-monitor-python,gmetad,ganglia-webfrontend" --after-install ./postinst  --license "Apache" --vendor "Megam Systems" --maintainer "<rajthilak@megam.io>" --url "https://www.megam.io/" --description "Megam monitor with ganglia." .
