#!/bin/sh

cat > //etc/init/megamanalytics.conf <<EOF
#!upstart
description "Megam logs(https://console.megam.io)"
author      "Megam Systems(https://www.megam.io)"

start on startup
stop on shutdown

script
    echo $$ > /var/run/megam/megamanalytics.pid
    exec sudo /usr/bin/node /usr/share/megam/megamanalytics/tap_monitor.js >> /var/log/megam/megamanalytics/megamanalytics.log 2>&1
end script

pre-start script
    # Date format same as (new Date()).toISOString() for consistency
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Starting" >> /var/log/megam/megamanalytics/megamanalytics.log
end script

pre-stop script
    rm /var/run/megam/megamanalytics.pid
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Stopping" >> /var/log/megam/megamanalytics/megamanalytics.log
end script
EOF



echo "starting megamanalytics"
sudo start megamanalytics
echo "started"
