#!/bin/sh

[ -d /var/log/megam/megamanalytics ] && rm -rf /var/log/megam/megamanalytics

[ -d /var/run/megam/megamanalytics ] && rm -rf /var/run/megamanalytics

[ -d /usr/share/megam/megamanalytics ] && rm -rf /usr/share/megam/megamanalytics

[ -d /etc/megamanalytics ] && rm -rf /etc/megamanalytics

[ -d /var/lib/megam/heka ] && rm -rf /var/lib/megam/heka

