#!/bin/sh


mkdir -p /var/log/megam/megamanalytics

chown megam:megam /var/log/megam/megamanalytics

mkdir -p /var/lib/megam/heka

cat > //var/lib/megam/heka/hekad.toml <<EOF
[LogOUT]
type = "LogstreamerInput"
log_directory = "/var/lib/megam/megamd/logs/"
file_match = '(?P<DomainName>[^/]+)/(?P<FileName>.*)\_out$'
differentiator = ["DomainName"]

[logERR]
type = "LogstreamerInput"
log_directory = "/var/lib/megam/megamd/logs/"
file_match = '(?P<DomainName>[^/]+)/(?P<FileName>.*)\_err$'
differentiator = ["DomainName"]


[AMQPOutput]
url = "amqp://guest:guest@localhost/"
exchange = "test_tom"
queue = true
exchangeType = "fanout"
message_matcher = 'TRUE'
encoder = "JsonEncoder"

[JsonEncoder]
fields = [ "Timestamp", "Type", "Logger", "Payload", "Hostname" ]
EOF

cat > //var/lib/megam/heka/megam_heka <<EOF
hekad -config /var/lib/megam/heka/hekad.toml
EOF
chmod 755 /var/lib/megam/heka/megam_heka


cat > //etc/init/megamheka.conf <<EOF
#!upstart
description "Megam heka"
author      "Megam Systems"

start on startup
stop on shutdown

script
    echo $$ > /var/run/megam/megamanalytics/heka.pid
    exec sudo /var/lib/megam/heka/megam_heka >> /var/log/megam/megamanalytics/heka.log 2>&1
end script

pre-start script
    # Date format same as (new Date()).toISOString() for consistency
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Starting" >> /var/log/megam/megamanalytics/heka.log
end script

pre-stop script
    rm /var/run/megam/megamanalytics/heka.pid
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Stopping" >> /var/log/megam/megamanalytics/heka.log
end script

EOF

start megamheka
