require "rake"
require "../../version.rb"
require "./config.rb"
puts ">> ------------- [#{MegamPkg::Ger::CONFIG[:name]} #{MegamPkg::Ger::VERSION}]"
task :default => :centos7

build_dir ="build"
centos7_dir ="7"
build_centos7_dir ="build/7"

task :clean do
  rm_rf build_centos7_dir
  rm_rf build_dir
end

task :centos7 => [:initcentos7_setup, :initcib, :clone] do
  system './g', MegamPkg::Ger::CONFIG[:name], MegamPkg::Ger::VERSION
  system './ng', MegamPkg::Ger::CONFIG[:name_node], MegamPkg::Ger::VERSION
end

task :initcentos7_setup do
  mkdir_p build_dir
  mkdir_p build_centos7_dir
  Rake::FileList[centos7_dir +"/**"].each do |f|
    target = File.join build_centos7_dir,  File.basename(f)
    cp_r f, target
  end
  Dir.chdir build_centos7_dir
end



task :initcib do
  mkdir_p "cloudinabox/src/github.com/megamsys"
end

task :clone do
  if !File.exists? 'cloudinabox/src/github.com/megamsys/cloudinabox/'
   Dir.chdir 'cloudinabox/src/github.com/megamsys'
   system "git clone " + MegamPkg::Ger::CONFIG[:git]
 end
 Dir.chdir '../../../../'
end

task :copydeb do
  if !File.exists? '*.deb'
   cp_r './cloudinabox/*.deb' '../../../'
  end
end
