#!/bin/bash

mkdir -p /var/lib/megam/cadvisor

#chown megam:megam /var/run/megam/cadvisor

#chown megam:megam /var/log/megam/cadvisor



if [ -d "/etc/chef-server" ]; then

  chef-server-ctl reconfigure

  chef-server-ctl restart

  unzip /usr/share/megam/cadvisor/conf/chef-repo.zip -d /var/lib/megam/cadvisor

  set -e

  chef_repo_dir=`find /var/lib/megam/cadvisor  -name chef-repo  | awk -F/ -vOFS=/ 'NF-=0' | sort -u`

  cp /etc/chef-server/*.pem $chef_repo_dir

  git clone https://github.com/megamsys/chef-repo $chef_repo_dir

  gem install knife

  knife cookbook upload --all -c $chef_repo_dir

fi

while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
		[ "$Mask" = "00000000" ] && \
		interface="$Iface" && \
		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
		ipaddr=${ipaddr#* inet } && \
		ipaddr=${ipaddr%%/*} && \
		break
	done < /proc/net/route



cat > //var/lib/megam/cadvisor.env <<EOF
ETCD_ADDR="$ipaddr:4001"
ETCD_BIND_ADDR="$ipaddr:4001"
ETCD_PEER_ADDR="$ipaddr:7001"
ETCD_PEER_BIND_ADDR="$ipaddr:7001"
EOF

chmod 755 /var/lib/megam/cadvisor.env

systemctl start cadvisor.service || echo "cadvisor could not be started. Try manually with service cadvisor start" >/dev/stdout
