#!/bin/sh

if [ -d "/usr/share/megam/megamd" ]; then
  rm -r /usr/share/megam/megamd
fi

if [ -d "/var/lib/megam/megamd" ]; then
  rm -r /var/lib/megam/megamd
fi

if [ -d "/var/log/megam/megamd" ]; then
  rm -r /var/log/megam/megamd
fi
