#!/bin/bash

mkdir -p /var/lib/megam/megamd

#chown megam:megam /var/run/megam/megamd

#chown megam:megam /var/log/megam/megamd

initctl reload-configuration

if [ -d "/etc/chef-server" ]; then

  chef-server-ctl reconfigure

  chef-server-ctl restart

  unzip /usr/share/megam/megamd/conf/chef-repo.zip -d /var/lib/megam/megamd

  set -e

  chef_repo_dir=`find /var/lib/megam/megamd  -name chef-repo  | awk -F/ -vOFS=/ 'NF-=0' | sort -u`

  cp /etc/chef-server/*.pem $chef_repo_dir
  
  git clone https://github.com/megamsys/chef-repo $chef_repo_dir

  gem install knife

  knife cookbook upload --all -c $chef_repo_dir

fi

while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
		[ "$Mask" = "00000000" ] && \
		interface="$Iface" && \
		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
		ipaddr=${ipaddr#* inet } && \
		ipaddr=${ipaddr%%/*} && \
		break
	done < /proc/net/route



cat > //var/lib/megam/env.sh <<EOF
initctl set-env ETCD_ADDR="$ipaddr:4001"
initctl set-env ETCD_BIND_ADDR="$ipaddr:4001"
initctl set-env ETCD_PEER_ADDR="$ipaddr:7001"
initctl set-env ETCD_PEER_BIND_ADDR="$ipaddr:7001"
EOF

chmod 755 /var/lib/megam/env.sh


#Gem install
gem install chef --no-ri --no-rdoc
mkdir -p /var/lib/megam/gems
cd /var/lib/megam/gems
set -- https://s3-ap-southeast-1.amazonaws.com/megampub/gems/fog.gem https://s3-ap-southeast-1.amazonaws.com/megampub/gems/knife-ec2.gem https://s3-ap-southeast-1.amazonaws.com/megampub/gems/knife-gogrid-0.1.0.gem https://s3-ap-southeast-1.amazonaws.com/megampub/gems/knife-google-1.3.1.gem https://s3-ap-southeast-1.amazonaws.com/megampub/gems/knife-hp.gem https://s3-ap-southeast-1.amazonaws.com/megampub/gems/knife-opennebula-0.1.0.gem https://s3-ap-southeast-1.amazonaws.com/megampub/gems/profitbricks-1.1.0.20130930123843.gem https://s3-ap-southeast-1.amazonaws.com/megampub/gems/knife-profitbricks-0.3.0.gem
while [ $# -gt 0 ]
do
        wget $1
        gem install ${1##*/} --no-ri --no-rdoc
        shift;
done





service megamd start || echo "megamd could not be started. Try manually with service megamd start"
