#!/bin/bash

mkdir -p /var/lib/megam/

cat >/var/lib/megam/env.sh <<EOF
MEGAM_HOME=''/var/lib/megam/'
HOST='localhost'
EOF

cp /etc/init.d/verticegulpd.service /etc/systemd/system/

echo " installed successfully"
#systemctl start .service || echo " could not be started. Try manually with service  start" >/dev/stdout
