#!/bin/sh

if [ -d "/usr/share/megam/" ]; then
  rm -r /usr/share/megam/
fi

if [ -d "/var/lib/megam/" ]; then
  rm -r /var/lib/megam/
fi

if [ -d "/var/run/megam/" ]; then
  rm -r /var/run/megam/
fi

if [ -d "/var/log/megam/" ]; then
  rm -r /var/log/megam/
fi

if [ -f "/etc/systemd/system/verticegulpd.service" ]; then
  rm /etc/systemd/system/verticegulpd.service
fi
