#!/bin/sh

TMP_BUILD_HOME=./usr/share/megam/$1

mkdir -p $TMP_BUILD_HOME
mkdir -p $TMP_BUILD_HOME/log

#just copy what you want.
cp  ./nilavu/config.ru $TMP_BUILD_HOME
cp  ./nilavu/Gemfile $TMP_BUILD_HOME
cp  ./nilavu/Gemfile.lock $TMP_BUILD_HOME
cp  ./nilavu/g $TMP_BUILD_HOME
cp  ./nilavu/License $TMP_BUILD_HOME
cp  ./nilavu/Rakefile $TMP_BUILD_HOME
cp  ./nilavu/README.md $TMP_BUILD_HOME

cp -r ./nilavu/app $TMP_BUILD_HOME
cp -r ./nilavu/config $TMP_BUILD_HOME
cp -r ./nilavu/public $TMP_BUILD_HOME
cp -r ./nilavu/vendor $TMP_BUILD_HOME
cp  ./mkoye.sh $TMP_BUILD_HOME

cd $TMP_BUILD_HOME

#this is needed for rake assets:clean..
export MEGAM_HOME="$PWD/config"

#install the gems inside a directory called vendor/bundle
bundle install --retry 3 --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j2 --deployment --jobs 4

#clean and precompile assets, we will have to shift it to a CDN
rake assets:clean
rake tmp:clear
rake assets:precompile RAILS_ENV=production

#screwy and good too in a sense we package the ruby nilavu will use.
mv mkoye.sh vendor
cd vendor
./mkoye.sh

#clean tmp files
cd ../
rm -rf $TMP_BUILD_HOME/tmp
cd ../../../../
rm -rf ./nilavu

fpm -s dir -t deb -n $1 -v $2 --after-install ./postinst --after-remove ./postrm  --exclude "**/.git**" --license "Apache" --vendor "Megam Systems" --maintainer="Thomas Alrin<thomasalrin@megam.io>, Raj Thilak <rajthilak@megam.io>, Kishorekumar Neelamegam<nkishore@megam.io>, Yeshwanth kumar <getyesh@megam.io>, Megam Systems <info@megam.io>" --url "https://www.megam.io/" --deb-upstart ./etc/init/megamnilavu --description "Megam Nilavu - Web as (https://console.megam.io)" $TMP_BUILD_HOME
