#!/bin/sh
set -e

MEGAM_INSTALLHOME=/usr/share/megam
MEGAMHOME=/var/lib/megam
MEGAM_GROUP=megam
MEGAM_USER=megam

disable_megamuser() {
    if getent passwd $MEGAM_USER > /dev/null 2>&1; then
        usermod --shell /bin/false $MEGAM_USER
    fi
}

if [ "$1" = "purge" ]; then

    # purge stats overrides
    # Don't delete oneadmin or cloud group for now
    # See http://wiki.debian.org/AccountHandlingInMaintainerScripts
    # ... just disable account
    disable_megamuser

    # Purge megam  files
    rm -rf $MEGAMHOME/verticegateway
    rm -rf $MEGAMHOME/vertice
    rm -rf $MEGAM_INSTALLHOME 2>/dev/null || true
    rm -rf $MEGAMHOME 2>/dev/null || true
    rm -rf /var/run/megam
    rm -rf /var/log/megam
    
fi
