#!/bin/bash

mkdir -p ./usr/share/megam/cadvisor/bin



#fpm -s dir -t rpm -n cadvisor -v 1.0 -d "verticecommon, rabbitmq-server, megametcd, unzip" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --license "Apache" --vendor "Megam Systems" --maintainer "<rajthilak@megam.io>" --url "https://www.megam.io" --description "The engine for Megam" ./usr/share/megam/cadvisor
fpm -s dir -t rpm -n $1 -v $2 -d "verticecommon, cgroup-bin" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --deb-upstart ./etc/init/cadvisor --license "Apache" --vendor "Megam Systems" --maintainer "Megam Maintainer info@megam.io" --url "https://www.megam.io/" --description "The engine for Megam" ./usr/share/megam/cadvisor
