#!/bin/sh

while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
		[ "$Mask" = "00000000" ] && \
		interface="$Iface" && \
		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
		ipaddr=${ipaddr#* inet } && \
		ipaddr=${ipaddr%%/*} && \
		break
done < /proc/net/route

mv /usr/share/megam/nsqd/nsqlookupd /etc/init/nsqlookupd.conf
mv /usr/share/megam/nsqd/nsqadmin  /etc/init/nsqadmin.conf
mkdir /var/lib/megam/nsqd
cat > /var/lib/megam/env.sh <<EOF
initctl set-env MEGAM_HOME='/var/lib/megam/'
initctl set-env MEGAM_NSLOOKUPD_IP="$ipaddr"
EOF

chmod 755 /var/lib/megam/env.sh

initctl reload-configuration
echo "nsqd not yet started. Try manually 'service nsqd start'"
