#!/bin/bash

mkdir -p ./usr/share/megam/cadvisor/bin

cd cadvisor/src/github.com/megamsys/cadvisor

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/cadvisor.git

#make build

#cp -rf ./conf/ ../../../../../usr/share/megam/cadvisor
cp ~/cadvisor ../../../../../usr/share/megam/cadvisor/bin

cd ../../../../../

#cp riakstash ./usr/share/megam/cadvisor/bin
#cp riakstash.cron.d ./usr/share/megam/cadvisor/bin

fpm -s dir -t deb -n $1 -v $2 -d "megamcommon, unzip" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --deb-upstart ./etc/init/cadvisor --license "Apache" --vendor "Megam Systems" --maintainer "<rajthilak@megam.io>" --url "https://www.megam.io/" --description "The engine for Megam" ./usr/share/megam/cadvisor
