#!/bin/bash

mkdir -p ./usr/share/megam/cadvisor/bin

cd cadvisor/src/github.com/megamsys/cadvisor

# sometimes  the dependencies aren't getting pulled. Adding a master solved the problem.
git remote add master https://github.com/indykish/cadvisor.git

make build

#cp -rf ./conf/ ../../../../../usr/share/megam/cadvisor
cp cadvisor ../../../../../usr/share/megam/cadvisor/bin

cd ../../../../../

fpm -s dir -t deb --iteration $3 -n $1 -v $2 -d "verticecommon, cgroup-bin" --before-install ./preinst --after-install ./postinst --before-remove ./prerm --after-remove ./postrm --deb-upstart ./etc/init/cadvisor --license "Apache" --vendor "Megam Systems" --maintainer "Megam Maintainer info@megam.io" --url "https://www.megam.io/" --description "The engine for Megam" ./usr/share/megam/cadvisor
