#!/bin/sh
rm *.deb
fpm -s dir -t deb -n "megamcommon" -v 0.5 --after-install ./postinst --after-remove ./postrm --license "Apache" --vendor "Megam Systems" --maintainer "<rajthilak@megam.co.in>" --url "http://www.gomegam.com" --description "Megam common an empty package which just creates an user megam and group megam." ./usr/share/megam
