#!/bin/sh

set -e

MEGAMHOME=/var/lib/megam
MEGAM_INSTALLHOME=/usr/share/megam
MEGAM_GROUP=megam
MEGAM_USER=megam

mkdir -p /usr/share/megam
mkdir -p /var/log/megam
mkdir -p /var/run/megam
mkdir -p /var/lib/megam

create_megamgroup() {
    if ! getent group $MEGAM_GROUP > /dev/null 2>&1; then
        addgroup --system $MEGAM_GROUP
    fi
}

create_megamuser() {
         mkdir -p $MEGAMHOME
    if ! getent passwd $MEGAM_USER > /dev/null 2>&1; then
        adduser --system --ingroup $MEGAM_GROUP --home $MEGAMHOME --shell /bin/bash $MEGAM_USER
    else
        MEGAMHOME=`getent passwd $MEGAM_USER | cut -f6 -d:`
        # Renable user (give him a shell)
        usermod --shell /bin/bash $MEGAM_USER
        # Make sure MEGAMHOME exists, might have been removed on previous purge
        mkdir -p $MEGAMHOME
    fi
}

if [ "$1" = "configure" ]; then
    create_megamgroup
    create_megamuser

    if ! [ -d "$MEGAM_INSTALLHOME" ]; then
        mkdir "$MEGAM_INSTALLHOME"
    fi

    # Use dpkg-statoverride instead of direct chmod/chown
    if ! dpkg-statoverride --list $MEGAMHOME >/dev/null 2>&1; then
        dpkg-statoverride --update --add $MEGAM_USER root 755 $MEGAMHOME
    fi

    # Use dpkg-statoverride instead of direct chmod/chown
    if ! dpkg-statoverride --list $MEGAM_INSTALLHOME >/dev/null 2>&1; then
        dpkg-statoverride --update --add $MEGAM_USER root 755 $MEGAM_INSTALLHOME
    fi
fi
