#!/bin/bash

mkdir -p /var/lib/megam/megamd

initctl reload-configuration

cp /usr/share/megam/megamd/bin/riakstash /var/lib/megam/megamd

chmod +x /var/lib/megam/megamd/riakstash

crontab  /usr/share/megam/megamd/bin/riakstash.cron.d

rm /usr/share/megam/megamd/bin/riakstash.cron.d

#service megamd start || echo "megamd could not be started. Try manually with service megamd start"

cat >> /etc/systemd/system/megamd.service << EOF
#Place the megamd here /etc/systemd/system/megamd.service
[Unit]
Description=Megam megamd
After=network.target
After=runlevel2.target
After=runlevel3.target
After=runlevel4.target
After=runlevel5.target
[Service]
ExecStart=/usr/share/megam/megamd/bin/megamd start
ExecStopPost=rm -f /var/run/megam/megamd.pid
KillMode=mixed
EOF

systemctl enable megamgulpd.service 
systemctl start megamgulpd.service
