#!/bin/bash

mkdir -p /var/lib/megam/megamd

initctl reload-configuration

cp /usr/share/megam/megamd/bin/riakstash /var/lib/megam/megamd

chmod +x /var/lib/megam/megamd/riakstash

crontab  /usr/share/megam/megamd/bin/riakstash.cron.d

rm /usr/share/megam/megamd/bin/riakstash.cron.d

#service megamd start || echo "megamd could not be started. Try manually with service megamd start"

mv /etc/init.d/megamd.service /etc/systemd/system/

cat >> /var/lib/megam/env.sh << EOF
MEGAM_HOME='/var/lib/megam/'
EOF

chmod 0755 /var/lib/megam/env.sh

systemctl enable megamgulpd.service 
systemctl start megamgulpd.service
