#!/bin/sh

mkdir -p ./usr/share/megam/snowflake



fpm -s dir -t rpm -n megamsnowflake -v 0.1 -d "megamcommon,python,python-thrift" --before-install ./preinst --after-install ./postinst --before-remove ./prerm  --after-remove ./postrm --license "Apache" --vendor "Megam Systems" --maintainer "<info@megam.io>" --url "https://www.megam.io" --description "Python based unique id generator server based on Twitters snowflake. source : https://github.com/erans/pysnowflake.git" ./usr/share/megam/snowflake
